function sharpnessRightSym = sharpnessRightFunction(cr,kip,kap,kim,kam,kpi,kmi,kpa,kma)
%SHARPNESSRIGHTFUNCTION
%    SHARPNESSRIGHTSYM = SHARPNESSRIGHTFUNCTION(CR,KIP,KAP,KIM,KAM,KPI,KMI,KPA,KMA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    26-Apr-2021 12:46:31

t2 = cr.^2;
t3 = kam.*kap.*kma;
t4 = kam.*kap.*kpa;
t5 = kap.*kim.*kma;
t6 = kam.*kip.*kmi;
t7 = kam.*kip.*kpa;
t8 = kap.*kim.*kpi;
t9 = kam.*kma.*kmi;
t10 = kam.*kmi.*kpa;
t11 = kim.*kip.*kmi;
t12 = kim.*kip.*kpi;
t13 = kim.*kma.*kmi;
t14 = kim.*kma.*kpi;
t19 = cr.*kap.*kma.*kpi;
t22 = cr.*kip.*kmi.*kpa;
t23 = cr.*kap.*kpa.*kpi.*2.0;
t24 = cr.*kip.*kpa.*kpi.*2.0;
t15 = cr.*t4;
t16 = cr.*t7;
t17 = cr.*t8;
t18 = cr.*t10;
t20 = cr.*t12;
t21 = cr.*t14;
t25 = kap.*kpa.*kpi.*t2;
t26 = kip.*kpa.*kpi.*t2;
t27 = t3+t6+t9+t19;
t28 = t5+t11+t13+t22;
t29 = t4+t8+t10+t23;
t30 = t7+t12+t14+t24;
t31 = 1.0./t27;
t33 = t15+t17+t18+t25;
t34 = t16+t20+t21+t26;
t32 = t31.^2;
t35 = kip.*kmi.*kpa.*t31;
t36 = t28.*t31;
t37 = t29.*t31;
t38 = t30.*t31;
t41 = t31.*t33;
t42 = t31.*t34;
t39 = kap.*kma.*kpi.*t28.*t32;
t43 = kap.*kma.*kpi.*t32.*t33;
t44 = kap.*kma.*kpi.*t32.*t34;
t47 = t36+t41+t42+1.0;
t40 = -t39;
t45 = -t43;
t46 = -t44;
t48 = 1.0./t47;
t49 = t48.^2;
t50 = t35+t37+t38+t40+t45+t46;
sharpnessRightSym = [t37.*t48+t45.*t48-t41.*t49.*t50,-t49.*t50];
