function RSymFull = RSymFunFull(cr,ki,ka,kp,km,wap,wip,wma,wpa,wmp)
%RSYMFUNFULL
%    RSYMFULL = RSYMFUNFULL(CR,KI,KA,KP,KM,WAP,WIP,WMA,WPA,WMP)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Oct-2021 13:40:03

RSymFull = reshape([-ka-cr.*kp.*2.0,cr.*kp,0.0,ka,cr.*kp,0.0,0.0,0.0,km,-km-cr.*kp-ka.*wap,ka.*wap,0.0,0.0,cr.*kp,0.0,0.0,0.0,ki.*wip,-ki.*wip-km.*wma-cr.*kp.*wpa,km.*wma,0.0,0.0,cr.*kp.*wpa,0.0,ki,0.0,cr.*kp.*wpa,-ki-cr.*kp.*wpa.*2.0,0.0,0.0,0.0,cr.*kp.*wpa,km,0.0,0.0,0.0,-km-cr.*kp-ka.*wap,cr.*kp,0.0,ka.*wap,0.0,km.*wmp,0.0,0.0,km.*wmp,km.*wmp.*-2.0-ka.*wap.^2,ka.*wap.^2,0.0,0.0,0.0,km.*wma.*wmp,0.0,0.0,ki.*wip.^2,-ki.*wip.^2-km.*wma.*wmp.*2.0,km.*wma.*wmp,0.0,0.0,0.0,km.*wma,ki.*wip,0.0,cr.*kp.*wpa,-ki.*wip-km.*wma-cr.*kp.*wpa],[8,8]);
