function RSym = RSymFun(cr,cw,a,km,kp,ka1,ki1,wmp,wpa1,wma1,wap1,wip1)
%RSYMFUN
%    RSYM = RSYMFUN(CR,CW,A,KM,KP,KA1,KI1,WMP,WPA1,WMA1,WAP1,WIP1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2021 12:32:35

t2 = a.*km;
t3 = cr.*kp;
t4 = cw.*kp;
t5 = ka1.*wap1;
t6 = ki1.*wip1;
t7 = km.*wma1;
t8 = t2.*wma1;
t9 = t3.*wpa1;
t10 = t4.*wpa1;
t11 = -t5;
t12 = -t6;
RSym = reshape([-ka1-t3-t4,t4,t3,ka1,0.0,0.0,t2,-t2+t11,0.0,0.0,t5,0.0,km,0.0,-km+t11,0.0,0.0,t5,ki1,0.0,0.0,-ki1-t9-t10,t10,t9,0.0,t6,0.0,t8,-t8+t12,0.0,0.0,0.0,t6,t7,0.0,-t7+t12],[6,6]);
