function out1 = RSymFun(cr,cw,alphaa,wip,wap,kim,kam,kpi,kmi,kpa,kma)
%RSYMFUN
%    OUT1 = RSYMFUN(CR,CW,ALPHAA,WIP,WAP,KIM,KAM,KPI,KMI,KPA,KMA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-Aug-2021 18:12:30

t2 = alphaa.*kma;
t3 = alphaa.*kmi;
t4 = cr.*kpa;
t5 = cr.*kpi;
t6 = cw.*kpa;
t7 = cw.*kpi;
t8 = kam.*wap;
t9 = kim.*wip;
t10 = -t8;
t11 = -t9;
out1 = reshape([-kam-t5-t7,t5,0.0,kam,0.0,t7,kmi,-kmi+t10,t8,0.0,0.0,0.0,0.0,t9,-kma+t11,kma,0.0,0.0,kim,0.0,t4,-kim-t4-t6,t6,0.0,0.0,0.0,0.0,t2,-t2+t11,t9,t3,0.0,0.0,0.0,t8,-t3+t10],[6,6]);
