function RSym = RSymFun(cr,cw,a,km,kp,ka1,ki1,ka2,ki2,wa21,wi21,wa12,wi12,wmp,wpa1,wma1,wap1,wip1,wpa2,wma2,wap2,wip2)
%RSYMFUN
%    RSYM = RSYMFUN(CR,CW,A,KM,KP,KA1,KI1,KA2,KI2,WA21,WI21,WA12,WI12,WMP,WPA1,WMA1,WAP1,WIP1,WPA2,WMA2,WAP2,WIP2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2021 14:07:42

t2 = a.*km;
t3 = cr.*kp;
t4 = cw.*kp;
t5 = ka2.*wa12;
t6 = ka1.*wa21;
t7 = ka1.*wap1;
t8 = ka2.*wap2;
t9 = ki2.*wi12;
t10 = ki1.*wi21;
t11 = ki1.*wip1;
t12 = ki2.*wip2;
t13 = km.*wma1;
t14 = km.*wma2;
t15 = t2.*wma1;
t16 = t2.*wma2;
t17 = t3.*wpa1;
t18 = t3.*wpa2;
t19 = t4.*wpa1;
t20 = t4.*wpa2;
t21 = t5.*wap2;
t22 = t6.*wap1;
t23 = t9.*wip2;
t24 = t10.*wip1;
t25 = t13.*wma2;
t29 = -t7;
t30 = -t8;
t31 = -t11;
t32 = -t12;
t26 = t15.*wma2;
t27 = t17.*wpa2;
t28 = t19.*wpa2;
t33 = -t21;
t34 = -t22;
t35 = -t23;
t36 = -t24;
RSym = reshape([-ka1-ka2-t3-t4,t4,t3,ka2,0.0,0.0,ka1,0.0,0.0,0.0,0.0,0.0,t2,-t2+t29+t30,0.0,0.0,t8,0.0,0.0,t7,0.0,0.0,0.0,0.0,km,0.0,-km+t29+t30,0.0,0.0,t8,0.0,0.0,t7,0.0,0.0,0.0,ki2,0.0,0.0,-ki2-t6-t18-t20,t20,t18,0.0,0.0,0.0,t6,0.0,0.0,0.0,t12,0.0,t16,-t16+t32+t34,0.0,0.0,0.0,0.0,0.0,t22,0.0,0.0,0.0,t12,t14,0.0,-t14+t32+t34,0.0,0.0,0.0,0.0,0.0,t22,ki1,0.0,0.0,0.0,0.0,0.0,-ki1-t5-t17-t19,t19,t17,t5,0.0,0.0,0.0,t11,0.0,0.0,0.0,0.0,t15,-t15+t31+t33,0.0,0.0,t21,0.0,0.0,0.0,t11,0.0,0.0,0.0,t13,0.0,-t13+t31+t33,0.0,0.0,t21,0.0,0.0,0.0,t10,0.0,0.0,t9,0.0,0.0,-t9-t10-t27-t28,t28,t27,0.0,0.0,0.0,0.0,t24,0.0,0.0,t23,0.0,t26,-t26+t35+t36,0.0,0.0,0.0,0.0,0.0,0.0,t24,0.0,0.0,t23,t25,0.0,-t25+t35+t36],[12,12]);
