function RSym8 = RSymFun(cr,wip1,wap1,kim1,kam1,wip2,wap2,kim2,kam2,kmi,wma1,wma2,kpi,wpa1,wpa2,wa12,wi12,wa21,wi21)
%RSYMFUN
%    RSYM8 = RSYMFUN(CR,WIP1,WAP1,KIM1,KAM1,WIP2,WAP2,KIM2,KAM2,KMI,WMA1,WMA2,KPI,WPA1,WPA2,WA12,WI12,WA21,WI21)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-Aug-2021 17:30:06

t2 = cr.*kpi;
t3 = kam1.*wa12;
t4 = kam2.*wa21;
t5 = kam1.*wap1;
t6 = kam2.*wap2;
t7 = kim1.*wi12;
t8 = kim2.*wi21;
t9 = kim1.*wip1;
t10 = kim2.*wip2;
t11 = kmi.*wma1;
t12 = kmi.*wma2;
t13 = t2.*wpa1;
t14 = t2.*wpa2;
t15 = t3.*wap1;
t16 = t4.*wap2;
t17 = t7.*wip1;
t18 = t8.*wip2;
t19 = t11.*wma2;
t20 = t13.*wpa2;
RSym8 = reshape([-kam1-kam2-t2,t2,0.0,kam1,kam2,0.0,0.0,0.0,kmi,-kmi-t5-t6,t5,0.0,0.0,t6,0.0,0.0,0.0,t9,-t9-t11-t16,t11,0.0,0.0,t16,0.0,kim1,0.0,t13,-kim1-t4-t13,0.0,0.0,0.0,t4,kim2,0.0,0.0,0.0,-kim2-t3-t14,t14,0.0,t3,0.0,t10,0.0,0.0,t12,-t10-t12-t15,t15,0.0,0.0,0.0,t18,0.0,0.0,t17,-t17-t18-t19,t19,0.0,0.0,0.0,t8,t7,0.0,t20,-t7-t8-t20],[8,8]);
