function RSym = RSymFun(cr,cw,a,ki,ka,kb,ku,wab,wib,wua,wba)
%RSYMFUN
%    RSYM = RSYMFUN(CR,CW,A,KI,KA,KB,KU,WAB,WIB,WUA,WBA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    24-Jun-2022 11:54:58

t2 = a.*ku;
t3 = cr.*kb;
t4 = cw.*kb;
t5 = ka.*wab;
t6 = ki.*wib;
t7 = ku.*wua;
t8 = t2.*wua;
t9 = t3.*wba;
t10 = t4.*wba;
t11 = -t5;
t12 = -t6;
RSym = reshape([-ka-t3-t4,t3,0.0,ka,0.0,t4,ku,-ku+t11,t5,0.0,0.0,0.0,0.0,t6,-t7+t12,t7,0.0,0.0,ki,0.0,t9,-ki-t9-t10,t10,0.0,0.0,0.0,0.0,t8,-t8+t12,t6,t2,0.0,0.0,0.0,t5,-t2+t11],[6,6]);
