function ssVec = sixStateSSFromMathematica_v2

% nStates = size(RSym,1);
% syms c positive
% for i = 1:nStates
%     for j = 1:nStates
%         if i~=j 
%             string = char(RSym(i,j));
%             if length(string)>=1
%                 eval(syms(string,'positive')
%             end
%         end
%     end
% end
syms cr cw a positive % cw a

% initialize baseline reaction rates
syms ki ka ku kb positive

% initialize interaction terms
syms wab wib wba wua positive

ssVec = [a.*ki.*ku.*(ki.*(ki+(cr+cw).*kb.*wba).*wib.^2+(ki.*(ku+a.*ku+2.* ...
  ka.*wab)+kb.*(a.*cr.*ku+cw.*ku+(cr+cw).*ka.*wab).*wba).*wib.*wua+( ...
  ku+ka.*wab).*(a.*ku+ka.*wab).*wua.^2).*(cw.*kb.*(ka.*wab+ki.*wib) ...
  .*(ki.*(ki+(ka+(cr+cw).*kb).*wba).*wib+(ki.*(ku+ka.*wab)+(ka+cw.* ...
  kb).*ku.*wba+ka.*(ka+(cr+cw).*kb).*wab.*wba).*wua)+a.^2.*ku.*wua.* ...
  (cr.^2.*kb.^2.*wba.*(ka.*wab+ki.*wib)+(ka+ki).*ku.*(ki.*wib+(ku+ ...
  ka.*wab).*wua)+cr.*kb.*(ka.^2.*wab.*wba+ki.^2.*wib+ka.*ki.*(wab+ ...
  wba.*wib)+ki.*ku.*(wba.*wib+wua)+ka.*ku.*(wba+wab.*wua)))+a.*( ...
  cr.^2.*kb.^2.*wba.*(ka.*wab+ki.*wib).*(ki.*wib+ka.*wab.*wua)+cr.* ...
  kb.*(ki.*wib.*(ka.*ki.*wab+ka.*(ku+(ka+cw.*kb).*wab).*wba+ki.*(ki+ ...
  (ka+cw.*kb+ku).*wba).*wib)+(ka.*wab.*(ka.*ki.*wab+(ka+2.*cw.*kb).* ...
  ku.*wba+ka.*(ka+cw.*kb).*wab.*wba)+ki.*(ka.*ku.*wab+ki.*(ku+ka.* ...
  wab)+2.*cw.*kb.*ku.*wba+ka.*(ka+cw.*kb+ku).*wab.*wba).*wib).*wua+ ...
  ka.*ku.*wab.*(ki+ka.*wab).*wua.^2)+ku.*(ki.*wib+(ku+ka.*wab).*wua) ...
  .*((ka+ki).*(ki.*wib+ka.*wab.*wua)+cw.*kb.*(ka.*wba+ki.*wba.*wib+ ...
  ki.*wua+ka.*wab.*wua)))).^(-1),a.*cr.*kb.*ki.*(ki.*(ki+(ka+(cr+cw) ...
  .*kb).*wba).*wib.^2+(ki.*(ku+a.*ku+ka.*wab)+(cw.*kb.*ku+a.*(ka+ ...
  cr.*kb).*ku+ka.*(ka+(cr+cw).*kb).*wab).*wba).*wib.*wua+ku.*(a.*ku+ ...
  ka.*wab).*wua.^2).*(cw.*kb.*(ka.*wab+ki.*wib).*(ki.*(ki+(ka+(cr+ ...
  cw).*kb).*wba).*wib+(ki.*(ku+ka.*wab)+(ka+cw.*kb).*ku.*wba+ka.*( ...
  ka+(cr+cw).*kb).*wab.*wba).*wua)+a.^2.*ku.*wua.*(cr.^2.*kb.^2.* ...
  wba.*(ka.*wab+ki.*wib)+(ka+ki).*ku.*(ki.*wib+(ku+ka.*wab).*wua)+ ...
  cr.*kb.*(ka.^2.*wab.*wba+ki.^2.*wib+ka.*ki.*(wab+wba.*wib)+ki.* ...
  ku.*(wba.*wib+wua)+ka.*ku.*(wba+wab.*wua)))+a.*(cr.^2.*kb.^2.* ...
  wba.*(ka.*wab+ki.*wib).*(ki.*wib+ka.*wab.*wua)+cr.*kb.*(ki.*wib.*( ...
  ka.*ki.*wab+ka.*(ku+(ka+cw.*kb).*wab).*wba+ki.*(ki+(ka+cw.*kb+ku) ...
  .*wba).*wib)+(ka.*wab.*(ka.*ki.*wab+(ka+2.*cw.*kb).*ku.*wba+ka.*( ...
  ka+cw.*kb).*wab.*wba)+ki.*(ka.*ku.*wab+ki.*(ku+ka.*wab)+2.*cw.* ...
  kb.*ku.*wba+ka.*(ka+cw.*kb+ku).*wab.*wba).*wib).*wua+ka.*ku.*wab.* ...
  (ki+ka.*wab).*wua.^2)+ku.*(ki.*wib+(ku+ka.*wab).*wua).*((ka+ki).*( ...
  ki.*wib+ka.*wab.*wua)+cw.*kb.*(ka.*wba+ki.*wba.*wib+ki.*wua+ka.* ...
  wab.*wua)))).^(-1),a.*cr.*ka.*kb.*(ki.^2.*wab.*wib+ki.*(ku+(ka+( ...
  cr+cw).*kb).*wab).*wba.*wib+ki.*wab.*(a.*ku+ka.*wab).*wua+(a.*ku.* ...
  (ku+ka.*wab+cr.*kb.*wab)+wab.*((ka+cw.*kb).*ku+ka.*(ka+(cr+cw).* ...
  kb).*wab)).*wba.*wua).*(cw.*kb.*(ka.*wab+ki.*wib).*(ki.*(ki+(ka+( ...
  cr+cw).*kb).*wba).*wib+(ki.*(ku+ka.*wab)+(ka+cw.*kb).*ku.*wba+ka.* ...
  (ka+(cr+cw).*kb).*wab.*wba).*wua)+a.^2.*ku.*wua.*(cr.^2.*kb.^2.* ...
  wba.*(ka.*wab+ki.*wib)+(ka+ki).*ku.*(ki.*wib+(ku+ka.*wab).*wua)+ ...
  cr.*kb.*(ka.^2.*wab.*wba+ki.^2.*wib+ka.*ki.*(wab+wba.*wib)+ki.* ...
  ku.*(wba.*wib+wua)+ka.*ku.*(wba+wab.*wua)))+a.*(cr.^2.*kb.^2.* ...
  wba.*(ka.*wab+ki.*wib).*(ki.*wib+ka.*wab.*wua)+cr.*kb.*(ki.*wib.*( ...
  ka.*ki.*wab+ka.*(ku+(ka+cw.*kb).*wab).*wba+ki.*(ki+(ka+cw.*kb+ku) ...
  .*wba).*wib)+(ka.*wab.*(ka.*ki.*wab+(ka+2.*cw.*kb).*ku.*wba+ka.*( ...
  ka+cw.*kb).*wab.*wba)+ki.*(ka.*ku.*wab+ki.*(ku+ka.*wab)+2.*cw.* ...
  kb.*ku.*wba+ka.*(ka+cw.*kb+ku).*wab.*wba).*wib).*wua+ka.*ku.*wab.* ...
  (ki+ka.*wab).*wua.^2)+ku.*(ki.*wib+(ku+ka.*wab).*wua).*((ka+ki).*( ...
  ki.*wib+ka.*wab.*wua)+cw.*kb.*(ka.*wba+ki.*wba.*wib+ki.*wua+ka.* ...
  wab.*wua)))).^(-1),a.*ka.*ku.*(ki.^2.*wib.^2+ki.*((1+a).*ku+2.* ...
  ka.*wab+(cr+cw).*kb.*wab).*wib.*wua+(a.*ku.*(ku+ka.*wab+cr.*kb.* ...
  wab)+wab.*((ka+cw.*kb).*ku+ka.*(ka+(cr+cw).*kb).*wab)).*wua.^2).*( ...
  cw.*kb.*(ka.*wab+ki.*wib).*(ki.*(ki+(ka+(cr+cw).*kb).*wba).*wib+( ...
  ki.*(ku+ka.*wab)+(ka+cw.*kb).*ku.*wba+ka.*(ka+(cr+cw).*kb).*wab.* ...
  wba).*wua)+a.^2.*ku.*wua.*(cr.^2.*kb.^2.*wba.*(ka.*wab+ki.*wib)+( ...
  ka+ki).*ku.*(ki.*wib+(ku+ka.*wab).*wua)+cr.*kb.*(ka.^2.*wab.*wba+ ...
  ki.^2.*wib+ka.*ki.*(wab+wba.*wib)+ki.*ku.*(wba.*wib+wua)+ka.*ku.*( ...
  wba+wab.*wua)))+a.*(cr.^2.*kb.^2.*wba.*(ka.*wab+ki.*wib).*(ki.* ...
  wib+ka.*wab.*wua)+cr.*kb.*(ki.*wib.*(ka.*ki.*wab+ka.*(ku+(ka+cw.* ...
  kb).*wab).*wba+ki.*(ki+(ka+cw.*kb+ku).*wba).*wib)+(ka.*wab.*(ka.* ...
  ki.*wab+(ka+2.*cw.*kb).*ku.*wba+ka.*(ka+cw.*kb).*wab.*wba)+ki.*( ...
  ka.*ku.*wab+ki.*(ku+ka.*wab)+2.*cw.*kb.*ku.*wba+ka.*(ka+cw.*kb+ku) ...
  .*wab.*wba).*wib).*wua+ka.*ku.*wab.*(ki+ka.*wab).*wua.^2)+ku.*( ...
  ki.*wib+(ku+ka.*wab).*wua).*((ka+ki).*(ki.*wib+ka.*wab.*wua)+cw.* ...
  kb.*(ka.*wba+ki.*wba.*wib+ki.*wua+ka.*wab.*wua)))).^(-1),cw.*ka.* ...
  kb.*(ki.^2.*wab.*wib+ki.*(a.*ku+(ka+(cr+cw).*kb).*wab).*wba.*wib+ ...
  ki.*wab.*(ku+ka.*wab).*wua+(a.*ku.*(ku+ka.*wab+cr.*kb.*wab)+wab.*( ...
  (ka+cw.*kb).*ku+ka.*(ka+(cr+cw).*kb).*wab)).*wba.*wua).*(cw.*kb.*( ...
  ka.*wab+ki.*wib).*(ki.*(ki+(ka+(cr+cw).*kb).*wba).*wib+(ki.*(ku+ ...
  ka.*wab)+(ka+cw.*kb).*ku.*wba+ka.*(ka+(cr+cw).*kb).*wab.*wba).* ...
  wua)+a.^2.*ku.*wua.*(cr.^2.*kb.^2.*wba.*(ka.*wab+ki.*wib)+(ka+ki) ...
  .*ku.*(ki.*wib+(ku+ka.*wab).*wua)+cr.*kb.*(ka.^2.*wab.*wba+ki.^2.* ...
  wib+ka.*ki.*(wab+wba.*wib)+ki.*ku.*(wba.*wib+wua)+ka.*ku.*(wba+ ...
  wab.*wua)))+a.*(cr.^2.*kb.^2.*wba.*(ka.*wab+ki.*wib).*(ki.*wib+ ...
  ka.*wab.*wua)+cr.*kb.*(ki.*wib.*(ka.*ki.*wab+ka.*(ku+(ka+cw.*kb).* ...
  wab).*wba+ki.*(ki+(ka+cw.*kb+ku).*wba).*wib)+(ka.*wab.*(ka.*ki.* ...
  wab+(ka+2.*cw.*kb).*ku.*wba+ka.*(ka+cw.*kb).*wab.*wba)+ki.*(ka.* ...
  ku.*wab+ki.*(ku+ka.*wab)+2.*cw.*kb.*ku.*wba+ka.*(ka+cw.*kb+ku).* ...
  wab.*wba).*wib).*wua+ka.*ku.*wab.*(ki+ka.*wab).*wua.^2)+ku.*(ki.* ...
  wib+(ku+ka.*wab).*wua).*((ka+ki).*(ki.*wib+ka.*wab.*wua)+cw.*kb.*( ...
  ka.*wba+ki.*wba.*wib+ki.*wua+ka.*wab.*wua)))).^(-1),cw.*kb.*ki.*( ...
  ki.*(ki+(ka+(cr+cw).*kb).*wba).*wib.^2+(ki.*(ku+a.*ku+ka.*wab)+( ...
  ka+(a.*cr+cw).*kb).*ku.*wba+ka.*(ka+(cr+cw).*kb).*wab.*wba).*wib.* ...
  wua+a.*ku.*(ku+ka.*wab).*wua.^2).*(cw.*kb.*(ka.*wab+ki.*wib).*( ...
  ki.*(ki+(ka+(cr+cw).*kb).*wba).*wib+(ki.*(ku+ka.*wab)+(ka+cw.*kb) ...
  .*ku.*wba+ka.*(ka+(cr+cw).*kb).*wab.*wba).*wua)+a.^2.*ku.*wua.*( ...
  cr.^2.*kb.^2.*wba.*(ka.*wab+ki.*wib)+(ka+ki).*ku.*(ki.*wib+(ku+ ...
  ka.*wab).*wua)+cr.*kb.*(ka.^2.*wab.*wba+ki.^2.*wib+ka.*ki.*(wab+ ...
  wba.*wib)+ki.*ku.*(wba.*wib+wua)+ka.*ku.*(wba+wab.*wua)))+a.*( ...
  cr.^2.*kb.^2.*wba.*(ka.*wab+ki.*wib).*(ki.*wib+ka.*wab.*wua)+cr.* ...
  kb.*(ki.*wib.*(ka.*ki.*wab+ka.*(ku+(ka+cw.*kb).*wab).*wba+ki.*(ki+ ...
  (ka+cw.*kb+ku).*wba).*wib)+(ka.*wab.*(ka.*ki.*wab+(ka+2.*cw.*kb).* ...
  ku.*wba+ka.*(ka+cw.*kb).*wab.*wba)+ki.*(ka.*ku.*wab+ki.*(ku+ka.* ...
  wab)+2.*cw.*kb.*ku.*wba+ka.*(ka+cw.*kb+ku).*wab.*wba).*wib).*wua+ ...
  ka.*ku.*wab.*(ki+ka.*wab).*wua.^2)+ku.*(ki.*wib+(ku+ka.*wab).*wua) ...
  .*((ka+ki).*(ki.*wib+ka.*wab.*wua)+cw.*kb.*(ka.*wba+ki.*wba.*wib+ ...
  ki.*wua+ka.*wab.*wua)))).^(-1)];
