function RSym = RSymFun(cr,cw,a,ki,ka,kp,km,wap,wip,wma,wpa,wmp,wa,wi)
%RSYMFUN
%    RSYM = RSYMFUN(CR,CW,A,KI,KA,KP,KM,WAP,WIP,WMA,WPA,WMP,WA,WI)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    17-Feb-2022 12:26:39

t2 = a.*km;
t3 = cr.*kp;
t4 = cw.*kp;
t5 = ka.*wa;
t6 = ki.*wip;
t7 = km.*wma;
t8 = ka.*2.0;
t9 = wma.^2;
t10 = wpa.^2;
t12 = ki.*wi.*2.0;
t17 = ka.*wap.*-2.0;
t11 = t8.*wap;
t13 = t2.*wma;
t14 = t3.*wpa;
t15 = t4.*wpa;
t16 = t5.*wap;
t18 = -t6;
t19 = t7.*wma;
t20 = t6.*wi.*2.0;
t21 = t2.*t9;
t22 = t3.*t10;
t23 = t4.*t10;
t24 = -t16;
t25 = -t20;
RSym = reshape([-t3-t4-t8,t4,t3,t8,0.0,0.0,0.0,0.0,0.0,t2,-t2+t17,0.0,0.0,t11,0.0,0.0,0.0,0.0,km,0.0,-km+t17,0.0,0.0,t11,0.0,0.0,0.0,ki,0.0,0.0,-ki-t5-t14-t15,t15,t14,t5,0.0,0.0,0.0,t6,0.0,t13,-t13+t18+t24,0.0,0.0,t16,0.0,0.0,0.0,t6,t7,0.0,-t7+t18+t24,0.0,0.0,t16,0.0,0.0,0.0,t12,0.0,0.0,-t12-t22-t23,t23,t22,0.0,0.0,0.0,0.0,t20,0.0,t21,-t21+t25,0.0,0.0,0.0,0.0,0.0,0.0,t20,t19,0.0,-t19+t25],[9,9]);
