function RSymFull = RSymFunFull(cr,cw,a,ki,ka,kp,km,wap,wip,wma,wpa,wmp,wa,wi)
%RSYMFUNFULL
%    RSYMFULL = RSYMFUNFULL(CR,CW,A,KI,KA,KP,KM,WAP,WIP,WMA,WPA,WMP,WA,WI)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    17-Feb-2022 12:26:39

RSymFull = reshape([ka.*-2.0-cr.*kp-cw.*kp,cr.*kp,0.0,ka,0.0,cw.*kp,ka,0.0,0.0,0.0,0.0,0.0,km,-km-ka.*wap.*2.0,ka.*wap,0.0,0.0,0.0,0.0,ka.*wap,0.0,0.0,0.0,0.0,0.0,ki.*wip,-ki.*wip-km.*wma-ka.*wa.*wap,km.*wma,0.0,0.0,0.0,0.0,ka.*wa.*wap,0.0,0.0,0.0,ki,0.0,cr.*kp.*wpa,-ki-ka.*wa-cr.*kp.*wpa-cw.*kp.*wpa,cw.*kp.*wpa,0.0,0.0,0.0,0.0,ka.*wa,0.0,0.0,0.0,0.0,0.0,a.*km.*wma,-ki.*wip-a.*km.*wma-ka.*wa.*wap,ki.*wip,0.0,0.0,0.0,0.0,ka.*wa.*wap,0.0,a.*km,0.0,0.0,0.0,ka.*wap,-a.*km-ka.*wap.*2.0,0.0,0.0,0.0,0.0,0.0,ka.*wap,ki,0.0,0.0,0.0,0.0,0.0,-ki-ka.*wa-cr.*kp.*wpa-cw.*kp.*wpa,cr.*kp.*wpa,0.0,ka.*wa,0.0,cw.*kp.*wpa,0.0,ki.*wip,0.0,0.0,0.0,0.0,km.*wma,-ki.*wip-km.*wma-ka.*wa.*wap,ka.*wa.*wap,0.0,0.0,0.0,0.0,0.0,ki.*wi.*wip,0.0,0.0,0.0,0.0,ki.*wi.*wip,-km.*wma.^2-ki.*wi.*wip.*2.0,km.*wma.^2,0.0,0.0,0.0,0.0,0.0,ki.*wi,0.0,0.0,ki.*wi,0.0,cr.*kp.*wpa.^2,ki.*wi.*-2.0-cr.*kp.*wpa.^2-cw.*kp.*wpa.^2,cw.*kp.*wpa.^2,0.0,0.0,0.0,0.0,0.0,ki.*wi.*wip,0.0,0.0,0.0,0.0,a.*km.*wma.^2,-a.*km.*wma.^2-ki.*wi.*wip.*2.0,ki.*wi.*wip,0.0,0.0,0.0,0.0,0.0,ki.*wip,a.*km.*wma,0.0,0.0,0.0,ka.*wa.*wap,-ki.*wip-a.*km.*wma-ka.*wa.*wap],[12,12]);
