function RSym = RSymFun(cr,cw,a,km,kp,ka,ki,wa,wi,wpa1,wma1,wap1,wip1)
%RSYMFUN
%    RSYM = RSYMFUN(CR,CW,A,KM,KP,KA,KI,WA,WI,WPA1,WMA1,WAP1,WIP1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2021 14:25:35

t2 = a.*km;
t3 = cr.*kp;
t4 = cw.*kp;
t5 = ka.*wap1;
t6 = ki.*wip1;
t7 = km.*wma1;
t8 = t2.*wma1;
t9 = t3.*wpa1;
t10 = t4.*wpa1;
t11 = -t5;
t12 = -t6;
RSym = reshape([-ka-t3-t4,t3,t4,ka,0.0,0.0,km,-km+t11,0.0,0.0,t5,0.0,t2,0.0,-t2+t11,0.0,0.0,t5,ki,0.0,0.0,-ki-t9-t10,t9,t10,0.0,t6,0.0,t7,-t7+t12,0.0,0.0,0.0,t6,t8,0.0,-t8+t12],[6,6]);
