function entropyRateSym = entropyRateFunction(cr,ki,ka,kb,ku,wab,wib,wua,wba)
%ENTROPYRATEFUNCTION
%    ENTROPYRATESYM = ENTROPYRATEFUNCTION(CR,KI,KA,KB,KU,WAB,WIB,WUA,WBA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    23-Jun-2022 21:10:28

t2 = ki.*wib;
t3 = ku.*wua;
t4 = cr.^2;
t5 = kb.^2;
t6 = ki.^2;
t8 = ka.*wab.*wua;
t9 = 1.0./cr;
t10 = 1.0./ka;
t11 = 1.0./kb;
t12 = 1.0./ki;
t13 = 1.0./ku;
t14 = cr.*kb.*ki.*wab;
t15 = cr.*kb.*ku.*wba;
t16 = cr.*kb.*wab.*wua;
t20 = cr.*ka.*kb.*wab.*wba;
t7 = ki.*t3;
t17 = ki.*t8;
t18 = ki.*t2;
t21 = cr.*kb.*t2.*wba;
t24 = t4.*t5.*wab.*wba;
t25 = t2.*t4.*t5.*wba;
t26 = t2+t3+t8+t16;
t19 = cr.*kb.*t7;
t22 = cr.*kb.*t18;
t23 = ka.*t21;
t27 = 1.0./t26;
t28 = t7+t17+t18+t21;
t29 = t14+t15+t20+t24;
t30 = t19+t22+t23+t25;
t31 = t10.*t27.*t28;
t32 = t13.*t27.*t29;
t33 = t10.*t13.*t27.*t30;
t34 = t31+t32+t33+1.0;
t35 = 1.0./t34;
entropyRateSym = ki.*t35.*log(ki.*t10)+t2.*t32.*t35.*log((t2.*t10)./wab)+t27.*t28.*t35.*log(ka.*t12)+cr.*kb.*t31.*t35.*log(cr.*kb.*t13)+t27.*t29.*t35.*wua.*log((t3.*t9.*t11)./wba)+t10.*t27.*t30.*t35.*log(ku.*t9.*t11)+cr.*kb.*t35.*wba.*log((cr.*kb.*wba)./t3)+t13.*t27.*t30.*t35.*wab.*log((ka.*wab)./t2);
