function RSym = RSymFun(cr,cw,a,ki,ka,kb,ku,wab,wib,wua,wba)
%RSYMFUN
%    RSYM = RSYMFUN(CR,CW,A,KI,KA,KB,KU,WAB,WIB,WUA,WBA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    23-Jun-2022 21:09:25

t2 = cr.*kb;
t3 = ka.*wab;
t4 = ki.*wib;
t5 = ku.*wua;
t6 = t2.*wba;
RSym = reshape([-ka-t2,t2,0.0,ka,ku,-ku-t3,t3,0.0,0.0,t4,-t4-t5,t5,ki,0.0,t6,-ki-t6],[4,4]);
