function RSym = RSymFun(cr,kip,kap,kim,kam,kpi,kmi,kpa,kma)
%RSYMFUN
%    RSYM = RSYMFUN(CR,KIP,KAP,KIM,KAM,KPI,KMI,KPA,KMA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Aug-2021 11:41:14

t2 = cr.*kpa;
t3 = cr.*kpi;
RSym = reshape([-kam-t3,t3,0.0,kam,kmi,-kap-kmi,kap,0.0,0.0,kip,-kip-kma,kma,kim,0.0,t2,-kim-t2],[4,4]);
