function out1 = TauCycleFunction(cr,ki,ka,kb,ku,wab,wib,wua,wba)
%TAUCYCLEFUNCTION
%    OUT1 = TAUCYCLEFUNCTION(CR,KI,KA,KB,KU,WAB,WIB,WUA,WBA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    23-Jun-2022 21:10:25

t2 = cr.*kb;
t3 = ka.*ku;
t4 = ki.*wib;
t5 = ku.*wua;
t6 = cr.^2;
t7 = ka.^2;
t8 = kb.^2;
t9 = ki.^2;
t12 = ka.*wab.*wua;
t13 = 1.0./ka;
t14 = 1.0./ku;
t10 = t2.*wba;
t11 = ki.*t5;
t15 = ka.*t2.*wab;
t16 = ki.*t2.*wab;
t18 = t2.*wab.*wua;
t19 = ki.*t12;
t20 = t7.*wab;
t21 = ki.*t4;
t17 = ku.*t10;
t22 = t2.*t11;
t23 = ka.*t10.*wab;
t24 = t4.*t10;
t25 = t2.*t21;
t27 = t2.*t10.*wab;
t29 = t3+t15+t20;
t31 = t4+t5+t12+t18;
t26 = ka.*t24;
t28 = t2.*t24;
t30 = t11+t21+t24;
t32 = 1.0./t29;
t33 = 1.0./t31;
t36 = t16+t17+t23+t27;
t34 = 1.0./t30;
t35 = t19+t30;
t37 = t22+t25+t26+t28;
t39 = t14.*t33.*t36;
t38 = t13.*t33.*t35;
t40 = (t33.*t37)./t3;
t41 = t38+t39+t40+1.0;
t42 = 1.0./t41;
out1 = (ki.*t32.*t42.*(ku+t2+ka.*wab)+t4.*t32.*t39.*t42.*(ka+ku+t2))./(ki.*t42+t4.*t39.*t42)+(t33.*t34.*t35.*t42.*(t4+t5+t10)+t14.*t33.*t34.*t37.*t42.*wab.*(ki+t5+t10))./(t33.*t35.*t42+t14.*t33.*t37.*t42.*wab);
