function ETOFFMean = TauONFunction(cr,ki,ka,kb,ku,wab,wib,wua,wba)
%TAUONFUNCTION
%    ETOFFMEAN = TAUONFUNCTION(CR,KI,KA,KB,KU,WAB,WIB,WUA,WBA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    23-Jun-2022 21:10:15

t2 = ki.*wib;
t3 = ku.*wua;
t4 = cr.^2;
t5 = kb.^2;
t6 = ki.^2;
t7 = cr.*kb.*wba;
t9 = ka.*wab.*wua;
t10 = 1.0./ka;
t11 = 1.0./ku;
t12 = cr.*kb.*ki.*wab;
t14 = cr.*kb.*wab.*wua;
t8 = ki.*t3;
t13 = ku.*t7;
t15 = ki.*t9;
t16 = ki.*t2;
t18 = ka.*t7.*wab;
t19 = t2.*t7;
t22 = t4.*t5.*wab.*wba;
t23 = t2.*t4.*t5.*wba;
t25 = t2+t3+t9+t14;
t17 = cr.*kb.*t8;
t20 = cr.*kb.*t16;
t21 = ka.*t19;
t24 = t8+t16+t19;
t26 = 1.0./t25;
t29 = t12+t13+t18+t22;
t27 = 1.0./t24;
t28 = t15+t24;
t30 = t17+t20+t21+t23;
t32 = t11.*t26.*t29;
t31 = t10.*t26.*t28;
t33 = t10.*t11.*t26.*t30;
t34 = t31+t32+t33+1.0;
t35 = 1.0./t34;
ETOFFMean = (t26.*t27.*t28.*t35.*(t2+t3+t7)+t11.*t26.*t27.*t30.*t35.*wab.*(ki+t3+t7))./(t26.*t28.*t35+t11.*t26.*t30.*t35.*wab);
