function dmdc = calculateGradientActivator(rate_vec,c_vec)     

    dmdc = (c_vec.^2*rate_vec(1)*rate_vec(7)*(rate_vec(2) + rate_vec(6)) + (rate_vec(2)*...
        rate_vec(3) + rate_vec(5)*(rate_vec(3) + rate_vec(6)))*(rate_vec(4) + rate_vec(8)) + ...
   c_vec.*(rate_vec(1)*rate_vec(2)*(rate_vec(3) + rate_vec(4)) + rate_vec(1)*rate_vec(4)*(rate_vec(3) + rate_vec(6)) + ...
      rate_vec(5)*rate_vec(6)*rate_vec(7) + (rate_vec(2) + rate_vec(5) + rate_vec(6))*rate_vec(7)* ...
      rate_vec(8))).^2 ./...
      (c_vec.^2*rate_vec(1).^2*rate_vec(2)*rate_vec(3)*(rate_vec(2) + ...
      rate_vec(4))*rate_vec(7) + (rate_vec(2) + rate_vec(5))*(rate_vec(2)*rate_vec(3) + rate_vec(5)* ...
      (rate_vec(3) + rate_vec(6)))*rate_vec(7)*rate_vec(8)*(rate_vec(4) + rate_vec(8)) + ...
   rate_vec(1)*(-c_vec.^2*rate_vec(5)*rate_vec(6)*rate_vec(7).^2*rate_vec(8) + rate_vec(2).^2*rate_vec(3)* ...
    (rate_vec(4) + 2*c_vec*rate_vec(7))*(rate_vec(4) + rate_vec(8)) + ...
      rate_vec(2)*rate_vec(5)*(rate_vec(3)*(rate_vec(4) + 2*c_vec*rate_vec(7))*(rate_vec(4) + rate_vec(8)) + ...
         rate_vec(6)*((rate_vec(4) + c_vec*rate_vec(7)).^2 + (rate_vec(4) + 2*c_vec*rate_vec(7))*rate_vec(8)))));