function NonEqRatio = FidelityMaxNorm1(kon,koff,km,kp,c1)
% expression taken from activator_model_v2.nb

NonEqRatio = ...
   (koff+kon).*(koff+c1.*kon).^(-1).*(km+koff+kon+kp).*(km+koff+c1.* ...
  kon+kp).^(-1).*(((-1)+c1).*km.^3.*(koff+kon)+((-1)+c1).*km.*(koff+ ...
  kon).*(koff+kp).*(koff+kon+kp)+(((-1)+c1).^2.*km.^2.*(koff+kon) ...
  .^2.*(km+kp).*(km+koff+kp).*(km+koff+kon+kp).*(km+koff+c1.*kon+kp) ...
  ).^(1/2)+((-1)+c1).*km.^2.*(koff+kon).*(2.*koff+kon+2.*kp)).^(-2) ...
  .*(((-1)+c1).*km.^3.*(koff+kon)+((-1)+c1).*km.*(koff+kon).*(koff+ ...
  kp).*(koff+c1.*kon+kp)+(((-1)+c1).^2.*km.^2.*(koff+kon).^2.*(km+ ...
  kp).*(km+koff+kp).*(km+koff+kon+kp).*(km+koff+c1.*kon+kp)).^(1/2)+ ...
  ((-1)+c1).*km.^2.*(koff+kon).*(2.*koff+c1.*kon+2.*kp)).^2;