function RSym = RSymFun(cr,cw,b,kip,kap,kim,kam,kpi,kmi,kpa,kma,kep,kem,kdp,kdm)
%RSYMFUN
%    RSYM = RSYMFUN(CR,CW,B,KIP,KAP,KIM,KAM,KPI,KMI,KPA,KMA,KEP,KEM,KDP,KDM)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    02-Aug-2021 16:58:22

t2 = b.*kma;
t3 = b.*kmi;
t4 = cr.*kep;
t5 = cw.*kpa;
t6 = cw.*kpi;
t7 = -kam;
t8 = -kap;
t9 = -kdm;
t10 = -kdp;
t11 = kep.*8.0;
t12 = kep.*9.0;
t13 = -kim;
t14 = -kip;
t15 = -kma;
t16 = -kmi;
t17 = -t2;
t18 = -t3;
t19 = -t4;
t20 = -t5;
t21 = -t6;
t22 = -t11;
t23 = -t12;
RSym = reshape([t7+t19+t21+t22,t4,kep,kam,kep,t6,0.0,kep,kep,kep,kep,kep,kmi,t7+t16+t23,kam,kep,kep,kep,kep,0.0,kep,kep,kep,kep,kep,kim,t13+t15+t23,kma,kep,kep,kep,kep,0.0,kep,kep,kep,kim,kep,t4,t13+t19+t20+t22,t5,kep,kep,kep,kep,0.0,kep,kep,kep,kep,kep,t2,t13+t17+t23,kim,kep,kep,kep,kep,0.0,kep,t3,kep,kep,kep,kam,t7+t18+t23,kep,kep,kep,kep,kep,0.0,kdm,kep,kep,kep,kep,kep,t7+t9+t19+t21+t22,t4,kep,kam,kep,t6,kep,kdp,kep,kep,kep,kep,kmi,t8+t10+t16+t23,kap,kep,kep,kep,kep,kep,kdp,kep,kep,kep,kep,kip,t10+t14+t15+t23,kma,kep,kep,kep,kep,kep,kdm,kep,kep,kim,kep,t4,t9+t13+t19+t20+t22,t5,kep,kep,kep,kep,kep,kdp,kep,kep,kep,kep,t2,t10+t14+t17+t23,kip,kep,kep,kep,kep,kep,kdp,t3,kep,kep,kep,kap,t8+t10+t18+t23],[12,12]);
