function RSym8 = RSymFun(cr,wip,wap,kim,kam,kpi,kmi,kpa,kma,wma,wmi)
%RSYMFUN
%    RSYM8 = RSYMFUN(CR,WIP,WAP,KIM,KAM,KPI,KMI,KPA,KMA,WMA,WMI)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Aug-2021 11:07:25

t2 = cr.*kpa;
t3 = cr.*kpi;
t4 = kam.*wap;
t5 = kim.*wip;
t6 = kma.*wma;
t7 = kmi.*wmi;
t8 = wap.^2;
t9 = wip.^2;
t10 = -kma;
t11 = -kmi;
t12 = -t2;
t13 = -t3;
t14 = -t4;
t15 = -t5;
t16 = t4.*wap;
t17 = t5.*wip;
t18 = t11+t13+t14;
t19 = t10+t12+t15;
RSym8 = reshape([-kam-t3.*2.0,t3,0.0,kam,t3,0.0,0.0,0.0,kmi,t18,t4,0.0,0.0,t3,0.0,0.0,0.0,t5,t19,kma,0.0,0.0,t2,0.0,kim,0.0,t2,-kim-t2.*2.0,0.0,0.0,0.0,t2,kmi,0.0,0.0,0.0,t18,t3,0.0,t4,0.0,t7,0.0,0.0,t7,t7.*-2.0+t14.*wap,t16,0.0,0.0,0.0,t6,0.0,0.0,t17,t6.*-2.0+t15.*wip,t6,0.0,0.0,0.0,kma,t5,0.0,t2,t19],[8,8]);
