function RSymFull = RSymFunFull(cr,ki,ka,kp,km,wap,wip,wma,wpa,wa,wi)
%RSYMFUNFULL
%    RSYMFULL = RSYMFUNFULL(CR,KI,KA,KP,KM,WAP,WIP,WMA,WPA,WA,WI)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Oct-2021 13:40:14

RSymFull = reshape([ka.*-2.0-cr.*kp,cr.*kp,0.0,ka,ka,0.0,0.0,0.0,km,-km-ka.*wap.*2.0,ka.*wap,0.0,0.0,ka.*wap,0.0,0.0,0.0,ki.*wip,-ki.*wip-km.*wma-ka.*wa.*wap,km.*wma,0.0,0.0,ka.*wa.*wap,0.0,ki,0.0,cr.*kp.*wpa,-ki-ka.*wa-cr.*kp.*wpa,0.0,0.0,0.0,ka.*wa,ki,0.0,0.0,0.0,-ki-ka.*wa-cr.*kp.*wpa,cr.*kp.*wpa,0.0,ka.*wa,0.0,ki.*wip,0.0,0.0,km.*wma,-ki.*wip-km.*wma-ka.*wa.*wap,ka.*wa.*wap,0.0,0.0,0.0,ki.*wi.*wip,0.0,0.0,ki.*wi.*wip,-km.*wma.^2-ki.*wi.*wip.*2.0,km.*wma.^2,0.0,0.0,0.0,ki.*wi,ki.*wi,0.0,cr.*kp.*wpa.^2,ki.*wi.*-2.0-cr.*kp.*wpa.^2],[8,8]);
