function RSym = RSymFun(cr,ki,ka,kp,km,wap,wip,wma,wpa,wa,wi)
%RSYMFUN
%    RSYM = RSYMFUN(CR,KI,KA,KP,KM,WAP,WIP,WMA,WPA,WA,WI)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Oct-2021 13:40:13

t2 = cr.*kp;
t3 = ka.*wa;
t4 = ki.*wip;
t5 = km.*wma;
t6 = ka.*2.0;
t7 = wma.^2;
t8 = wpa.^2;
t10 = ki.*wi.*2.0;
t9 = t6.*wap;
t11 = t2.*wpa;
t12 = t3.*wap;
t13 = t5.*wma;
t14 = t4.*wi.*2.0;
t15 = t2.*t8;
RSym = reshape([-t2-t6,t2,t6,0.0,0.0,0.0,km,-km-ka.*wap.*2.0,0.0,t9,0.0,0.0,ki,0.0,-ki-t3-t11,t11,t3,0.0,0.0,t4,t5,-t4-t5-t12,0.0,t12,0.0,0.0,t10,0.0,-t10-t15,t15,0.0,0.0,0.0,t14,t13,-t13-t14],[6,6]);
