function RSym = RSymFun(cr,ki,ka,kp,km,wap,wip,wma,wpa,wa,wi)
%RSYMFUN
%    RSYM = RSYMFUN(CR,KI,KA,KP,KM,WAP,WIP,WMA,WPA,WA,WI)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Oct-2021 13:41:02

t2 = cr.*kp;
t3 = ki.*wip;
t4 = km.*wma;
t5 = ka.*4.0;
t6 = wa.^2;
t7 = wa.^3;
t8 = wi.^2;
t9 = wi.^3;
t10 = wma.^2;
t11 = wma.^3;
t13 = wpa.^2;
t14 = wpa.^3;
t16 = ka.*wa.*3.0;
t18 = ki.*wi.*2.0;
t12 = t10.^2;
t15 = t13.^2;
t17 = t5.*wap;
t19 = t2.*wpa;
t20 = ka.*t7;
t21 = t4.*wma;
t22 = t4.*t10;
t23 = t4.*t11;
t24 = t16.*wap;
t25 = t3.*wi.*2.0;
t26 = t2.*t13;
t27 = t2.*t14;
t30 = ka.*t6.*2.0;
t31 = ki.*t8.*3.0;
t32 = ki.*t9.*4.0;
t34 = t3.*t8.*3.0;
t35 = t3.*t9.*4.0;
t28 = t2.*t15;
t29 = t20.*wap;
t33 = t30.*wap;
RSym = reshape([-t2-t5,t2,t5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,km,-km-ka.*wap.*4.0,0.0,t17,0.0,0.0,0.0,0.0,0.0,0.0,ki,0.0,-ki-t16-t19,t19,t16,0.0,0.0,0.0,0.0,0.0,0.0,t3,t4,-t3-t4-ka.*wa.*wap.*3.0,0.0,t24,0.0,0.0,0.0,0.0,0.0,0.0,t18,0.0,-t18-t26-t30,t26,t30,0.0,0.0,0.0,0.0,0.0,0.0,t25,t21,-t21-t25-ka.*t6.*wap.*2.0,0.0,t33,0.0,0.0,0.0,0.0,0.0,0.0,t31,0.0,-t20-t27-t31,t27,t20,0.0,0.0,0.0,0.0,0.0,0.0,t34,t22,-t22-t29-t34,0.0,t29,0.0,0.0,0.0,0.0,0.0,0.0,t32,0.0,-t28-t32,t28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t35,t23,-t23-t35],[10,10]);
