function RSym = RSymFun(cr,cw,b,kip,kap,kim,kam,kpi,kmi,kpa,kma)
%RSYMFUN
%    RSYM = RSYMFUN(CR,CW,B,KIP,KAP,KIM,KAM,KPI,KMI,KPA,KMA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Apr-2021 13:51:02

t2 = b.*kma;
t3 = b.*kmi;
t4 = cr.*kpa;
t5 = cr.*kpi;
t6 = cw.*kpa;
t7 = cw.*kpi;
t8 = -kap;
t9 = -kip;
RSym = reshape([-kam-t5-t7,t5,0.0,kam,0.0,t7,kmi,-kmi+t8,kap,0.0,0.0,0.0,0.0,kip,-kma+t9,kma,0.0,0.0,kim,0.0,t4,-kim-t4-t6,t6,0.0,0.0,0.0,0.0,t2,-t2+t9,kip,t3,0.0,0.0,0.0,kap,-t3+t8],[6,6]);
