function RSym = RSymFun(cr,ki,ka,km,kp,wip,wap,wma,wpa)
%RSYMFUN
%    RSYM = RSYMFUN(CR,KI,KA,KM,KP,WIP,WAP,WMA,WPA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    23-Jun-2022 11:56:49

t2 = cr.*kp;
t3 = ka.*wap;
t4 = ki.*wip;
t5 = km.*wma;
t6 = t2.*wpa;
RSym = reshape([-ka-t2,t2,0.0,ka,km,-km-t3,t3,0.0,0.0,t4,-t4-t5,t5,ki,0.0,t6,-ki-t6],[4,4]);
