function RSym = RSymFun(cr,kip,kap,kim,kam,kpi,kpa,kmi,kma)
%RSYMFUN
%    RSYM = RSYMFUN(CR,KIP,KAP,KIM,KAM,KPI,KPA,KMI,KMA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Apr-2021 12:34:07

t2 = cr.*kpa;
t3 = cr.*kpi;
RSym = reshape([-kam-t3,t3,0.0,kam,kmi,-kap-kmi,kap,0.0,0.0,kip,-kip-kma,kma,kim,0.0,t2,-kim-t2],[4,4]);
