function productionRateSym = productionRateFunction(cr,kip,kap,kim,kam,kpi,kmi,kpa,kma)
%PRODUCTIONRATEFUNCTION
%    PRODUCTIONRATESYM = PRODUCTIONRATEFUNCTION(CR,KIP,KAP,KIM,KAM,KPI,KMI,KPA,KMA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    26-Apr-2021 17:35:13

t2 = cr.^2;
t3 = kam.*kap.*kma;
t4 = kap.*kim.*kma;
t5 = kam.*kip.*kmi;
t6 = kam.*kma.*kmi;
t7 = kim.*kip.*kmi;
t8 = kim.*kma.*kmi;
t9 = cr.*kam.*kap.*kpa;
t10 = cr.*kam.*kip.*kpa;
t11 = cr.*kap.*kim.*kpi;
t12 = cr.*kam.*kmi.*kpa;
t13 = cr.*kap.*kma.*kpi;
t14 = cr.*kim.*kip.*kpi;
t15 = cr.*kim.*kma.*kpi;
t16 = cr.*kip.*kmi.*kpa;
t17 = kap.*kpa.*kpi.*t2;
t18 = kip.*kpa.*kpi.*t2;
t19 = t3+t5+t6+t13;
t20 = t4+t7+t8+t16;
t21 = 1.0./t19;
t22 = t9+t11+t12+t17;
t23 = t10+t14+t15+t18;
t24 = t20.*t21;
t25 = t21.*t22;
t26 = t21.*t23;
t27 = t24+t25+t26+1.0;
t28 = 1.0./t27;
productionRateSym = t28+t25.*t28;
