function productionRateWrongSym = productionRateWrongFunction(cw,b,kip,kap,kim,kam,kpi,kmi,kpa,kma)
%PRODUCTIONRATEWRONGFUNCTION                     
%    PRODUCTIONRATEWRONGSYM = PRODUCTIONRATEWRONGFUNCTION(CW,B,KIP,KAP,KIM,KAM,KPI,KMI,KPA,KMA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    26-Apr-2021 17:35:14

t2 = cw.^2;
t3 = kam.*kap.*kma;
t4 = kap.*kim.*kma;
t5 = kam.*kip.*kmi;
t6 = kim.*kip.*kmi;
t7 = 1.0./b;
t8 = b.*kam.*kma.*kmi;
t9 = b.*kim.*kma.*kmi;
t10 = cw.*kam.*kap.*kpa;
t11 = cw.*kam.*kip.*kpa;
t12 = cw.*kap.*kim.*kpi;
t13 = cw.*kap.*kma.*kpi;
t14 = cw.*kim.*kip.*kpi;
t15 = cw.*kip.*kmi.*kpa;
t16 = b.*cw.*kam.*kmi.*kpa;
t17 = b.*cw.*kim.*kma.*kpi;
t18 = kap.*kpa.*kpi.*t2;
t19 = kip.*kpa.*kpi.*t2;
t20 = t3+t5+t8+t13;
t21 = t4+t6+t9+t15;
t22 = 1.0./t20;
t23 = t10+t12+t16+t18;
t24 = t11+t14+t17+t19;
t25 = t21.*t22;
t26 = t7.*t22.*t23;
t27 = t7.*t22.*t24;
t28 = t25+t26+t27+1.0;
t29 = 1.0./t28;
productionRateWrongSym = t29+t26.*t29;
