function RSym = RSymFun(cr,ki,ka,kp,km,wap,wip,wma,wpa,wmp,wa,wi)
%RSYMFUN
%    RSYM = RSYMFUN(CR,KI,KA,KP,KM,WAP,WIP,WMA,WPA,WMP,WA,WI)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Oct-2021 13:40:15

t2 = cr.*kp;
t3 = ka.*wa;
t4 = ki.*wip;
t5 = km.*wma;
t6 = ka.*2.0;
t7 = wap.^2;
t8 = wip.^2;
t9 = wma.^2;
t10 = wpa.^2;
t13 = ki.*wi.*2.0;
t14 = km.*wmp.*2.0;
t11 = t2.*2.0;
t12 = t6.*wap;
t15 = t2.*wpa;
t16 = t3.*wap;
t17 = t4.*wip;
t18 = t5.*wma;
t20 = t4.*wi.*2.0;
t21 = t5.*wmp.*2.0;
t22 = t2.*t10;
t23 = t3.*t7;
t24 = t6.*t7;
t19 = t11.*wpa;
t25 = t10.*t11;
t26 = t17.*wi.*2.0;
t27 = t18.*wmp.*2.0;
RSym = reshape([-t6-t11,t11,0.0,t6,0.0,0.0,0.0,0.0,0.0,km,-km-t2-ka.*wap.*2.0,t2,0.0,t12,0.0,0.0,0.0,0.0,0.0,t14,-t14-ka.*t7.*2.0,0.0,0.0,t24,0.0,0.0,0.0,ki,0.0,0.0,-ki-t3-t15.*2.0,t19,0.0,t3,0.0,0.0,0.0,t4,0.0,t5,-t4-t5-t15-t16,t15,0.0,t16,0.0,0.0,0.0,t17,0.0,t21,-t17-t21-t23,0.0,0.0,t23,0.0,0.0,0.0,t13,0.0,0.0,-t13-t22.*2.0,t25,0.0,0.0,0.0,0.0,0.0,t20,0.0,t18,-t18-t20-t22,t22,0.0,0.0,0.0,0.0,0.0,t26,0.0,t27,-t26-t27],[9,9]);
