function RSymWrong = RSymFunWrong(cw,b,kip,kap,kim,kam,kpi,kmi,kpa,kma)
%RSYMFUNWRONG
%    RSYMWRONG = RSYMFUNWRONG(CW,B,KIP,KAP,KIM,KAM,KPI,KMI,KPA,KMA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Aug-2021 11:41:14

t2 = b.*kma;
t3 = b.*kmi;
t4 = cw.*kpa;
t5 = cw.*kpi;
RSymWrong = reshape([-kam-t5,t5,0.0,kam,t3,-kap-t3,kap,0.0,0.0,kip,-kip-t2,t2,kim,0.0,t4,-kim-t4],[4,4]);
