function ETONMean = TauOFFFunction(cr,kip,kap,kim,kam,kpi,kmi,kpa,kma)
%TAUOFFFUNCTION
%    ETONMEAN = TAUOFFFUNCTION(CR,KIP,KAP,KIM,KAM,KPI,KMI,KPA,KMA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Apr-2021 12:57:33

t2 = cr.*kpi;
t3 = kam.*kap;
t4 = kam.*kmi;
t5 = cr.^2;
t8 = kap.*kim.*kma;
t11 = kim.*kip.*kmi;
t12 = kim.*kma.*kmi;
t14 = cr.*kam.*kip.*kpa;
t20 = cr.*kip.*kmi.*kpa;
t6 = kap.*t2;
t7 = kma.*t3;
t9 = kip.*t4;
t10 = kma.*t4;
t13 = cr.*kpa.*t3;
t16 = cr.*kpa.*t4;
t18 = kim.*kip.*t2;
t19 = kim.*kma.*t2;
t22 = cr.*kip.*kpa.*t2;
t26 = t8+t11+t12+t20;
t15 = kim.*t6;
t17 = kma.*t6;
t21 = cr.*kpa.*t6;
t23 = t3+t4+t6;
t29 = t14+t18+t19+t22;
t24 = 1.0./t23;
t25 = t7+t9+t10+t17;
t28 = t13+t15+t16+t21;
t27 = 1.0./t25;
t30 = t26.*t27;
t31 = t27.*t28;
t32 = t27.*t29;
t33 = t30+t31+t32+1.0;
t34 = 1.0./t33;
ETONMean = (kim.*t24.*t34.*(kap+kmi+t2)+kip.*t24.*t31.*t34.*(kam+kmi+t2))./(kim.*t34+kip.*t31.*t34);
