function ETOFFMean = TauONFunction(k23,k43)
%TAUONFUNCTION
%    ETOFFMEAN = TAUONFUNCTION(K23,K43)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    02-Feb-2021 10:09:20

ETOFFMean = 1.0./(k23+k43);
