function RSym = RSymFun(cr,ki,ka,kp,km,wap,wip,wma,wpa,wmp)
%RSYMFUN
%    RSYM = RSYMFUN(CR,KI,KA,KP,KM,WAP,WIP,WMA,WPA,WMP)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Oct-2021 13:40:07

t2 = cr.*kp;
t3 = ka.*wap;
t4 = ki.*wip;
t5 = km.*wma;
t6 = wap.^2;
t7 = wap.^3;
t9 = wip.^2;
t10 = wip.^3;
t12 = wmp.^2;
t13 = wmp.^3;
t17 = km.*wmp.*2.0;
t8 = t6.^2;
t11 = t9.^2;
t14 = t2.*2.0;
t15 = t2.*3.0;
t16 = t2.*4.0;
t18 = t2.*wpa;
t19 = t3.*wap;
t20 = t3.*t6;
t21 = t3.*t7;
t22 = t4.*wip;
t23 = t4.*t9;
t24 = t4.*t10;
t28 = t5.*wmp.*2.0;
t29 = km.*t12.*3.0;
t30 = km.*t13.*4.0;
t31 = t5.*t12.*3.0;
t32 = t5.*t13.*4.0;
t25 = t14.*wpa;
t26 = t15.*wpa;
t27 = t16.*wpa;
RSym = reshape([-ka-t16,t16,0.0,0.0,0.0,ka,0.0,0.0,0.0,0.0,km,-km-t3-t15,t15,0.0,0.0,0.0,t3,0.0,0.0,0.0,0.0,t17,-t14-t17-t19,t14,0.0,0.0,0.0,t19,0.0,0.0,0.0,0.0,t29,-t2-t20-t29,t2,0.0,0.0,0.0,t20,0.0,0.0,0.0,0.0,t30,-t21-t30,0.0,0.0,0.0,0.0,t21,ki,0.0,0.0,0.0,0.0,-ki-t18.*4.0,t27,0.0,0.0,0.0,0.0,t4,0.0,0.0,0.0,t5,-t4-t5-t18.*3.0,t26,0.0,0.0,0.0,0.0,t22,0.0,0.0,0.0,t28,t18.*-2.0-t22-t28,t25,0.0,0.0,0.0,0.0,t23,0.0,0.0,0.0,t31,-t18-t23-t31,t18,0.0,0.0,0.0,0.0,t24,0.0,0.0,0.0,t32,-t24-t32],[10,10]);
