function productionRateWrongSym = productionRateWrongFunctionFourState(cw,a,ki,ka,kp,km,wi,wa,g)
%PRODUCTIONRATEWRONGFUNCTIONFOURSTATE
%    PRODUCTIONRATEWRONGSYM = PRODUCTIONRATEWRONGFUNCTIONFOURSTATE(CW,A,KI,KA,KP,KM,WI,WA,G)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    05-Aug-2021 19:19:11

t2 = cw.^2;
t3 = ki.^2;
t4 = kp.^2;
t5 = wa.^2;
t6 = cw.*ki.*kp;
t7 = a.*km.*wa;
t8 = 1.0./a;
t9 = 1.0./ka;
t10 = 1.0./km;
t13 = a.*cw.*km.*kp;
t15 = cw.*g.*ka.*kp.*wa;
t11 = ka.*t6;
t12 = ki.*t7;
t14 = g.*ka.*t5;
t16 = g.*t6.*wa;
t17 = cw.*kp.*t3;
t18 = cw.*g.*kp.*t5;
t20 = t6.*t7;
t21 = ki.*t2.*t4;
t22 = g.*t2.*t4.*wa;
t19 = ki.*t14;
t23 = ki+t7+t14+t18;
t26 = t13+t15+t16+t22;
t27 = t11+t17+t20+t21;
t24 = t3+t6+t12+t19;
t25 = 1.0./t23;
t28 = t9.*t24.*t25;
t29 = t8.*t10.*t25.*t26.*wa;
t30 = t8.*t9.*t10.*t25.*t27;
t31 = t28+t29+t30+1.0;
t32 = 1.0./t31;
productionRateWrongSym = t32+t29.*t32;
