function RSymNuc = RSymFun(cr,cw,a,ki,ka,kp,km,wi,wa,g)
%RSYMFUN
%    RSYMNUC = RSYMFUN(CR,CW,A,KI,KA,KP,KM,WI,WA,G)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    05-Aug-2021 19:19:12

t2 = a.*km;
t3 = cr.*kp;
t4 = cw.*kp;
t5 = g.*ka.*wa;
t6 = -km;
t7 = 1.0./wa;
t8 = -t2;
t9 = -t3;
t10 = -t4;
t11 = ki.*t7;
t12 = -t5;
t13 = -t11;
RSymNuc = reshape([-ka+t9+t10,t3,0.0,ka,0.0,t4,km,t6+t12,t5,0.0,0.0,0.0,0.0,t11,t6+t13,km,0.0,0.0,ki,0.0,t3,-ki+t9+t10,t4,0.0,0.0,0.0,0.0,t2,t8+t13,t11,t2,0.0,0.0,0.0,t5,t8+t12],[6,6]);
