function ssVecSymRight = ssVecFunction4StateRight(cr,ki,ka,kp,km,wi,wa,g)
%SSVECFUNCTION4STATERIGHT
%    SSVECSYMRIGHT = SSVECFUNCTION4STATERIGHT(CR,KI,KA,KP,KM,WI,WA,G)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    05-Aug-2021 19:19:10

t2 = km.*wa;
t3 = cr.^2;
t4 = ki.^2;
t5 = kp.^2;
t6 = wa.^2;
t7 = cr.*ki.*kp;
t8 = cr.*km.*kp;
t10 = 1.0./ka;
t11 = 1.0./km;
t14 = cr.*g.*ka.*kp.*wa;
t9 = ki.*t2;
t12 = ka.*t7;
t13 = g.*ka.*t6;
t15 = g.*t7.*wa;
t16 = t2.*t7;
t17 = cr.*kp.*t4;
t18 = cr.*g.*kp.*t6;
t20 = ki.*t3.*t5;
t21 = g.*t3.*t5.*wa;
t19 = ki.*t13;
t22 = ki+t2+t13+t18;
t25 = t12+t16+t17+t20;
t26 = t8+t14+t15+t21;
t23 = t4+t7+t9+t19;
t24 = 1.0./t22;
t27 = t10.*t23.*t24;
t28 = t11.*t24.*t26.*wa;
t29 = t10.*t11.*t24.*t25;
t30 = t27+t28+t29+1.0;
t31 = 1.0./t30;
ssVecSymRight = [t27.*t31;t29.*t31;t28.*t31;t31];
