function entropyRateSym = entropyRateFunction(cr,kip,kap,kim,kam,kpi,kmi,kpa,kma)
%ENTROPYRATEFUNCTION
%    ENTROPYRATESYM = ENTROPYRATEFUNCTION(CR,KIP,KAP,KIM,KAM,KPI,KMI,KPA,KMA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Apr-2021 12:57:44

t2 = cr.^2;
t3 = kam.*kap.*kma;
t4 = kap.*kim.*kma;
t5 = kam.*kip.*kmi;
t6 = kam.*kma.*kmi;
t7 = kim.*kip.*kmi;
t8 = kim.*kma.*kmi;
t9 = 1.0./cr;
t10 = cr.*kam.*kap.*kpa;
t11 = cr.*kam.*kip.*kpa;
t12 = cr.*kap.*kim.*kpi;
t13 = cr.*kam.*kmi.*kpa;
t14 = cr.*kap.*kma.*kpi;
t15 = cr.*kim.*kip.*kpi;
t16 = cr.*kim.*kma.*kpi;
t17 = cr.*kip.*kmi.*kpa;
t18 = kap.*kpa.*kpi.*t2;
t19 = kip.*kpa.*kpi.*t2;
t20 = t3+t5+t6+t14;
t21 = t4+t7+t8+t17;
t22 = 1.0./t20;
t23 = t10+t12+t13+t18;
t24 = t11+t15+t16+t19;
t25 = t21.*t22;
t26 = t22.*t23;
t27 = t22.*t24;
t28 = t25+t26+t27+1.0;
t29 = 1.0./t28;
entropyRateSym = kim.*t29.*log(kim./kam)+cr.*kpa.*t29.*log((cr.*kpa)./kma)+kma.*t26.*t29.*log((kma.*t9)./kpa)+kmi.*t27.*t29.*log((kmi.*t9)./kpi)+kam.*t25.*t29.*log(kam./kim)+kap.*t27.*t29.*log(kap./kip)+kip.*t26.*t29.*log(kip./kap)+cr.*kpi.*t25.*t29.*log((cr.*kpi)./kmi);
