function RSym = RSymFun(cr,cw,b,kip,kap,kim,kam,kpi,kmi,kpa,kma,ke,kdp,kdm)
%RSYMFUN
%    RSYM = RSYMFUN(CR,CW,B,KIP,KAP,KIM,KAM,KPI,KMI,KPA,KMA,KE,KDP,KDM)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    02-Aug-2021 16:58:50

t2 = b.*kma;
t3 = b.*kmi;
t4 = cr.*kpa;
t5 = cr.*kpi;
t6 = cw.*kpa;
t7 = cw.*kpi;
t8 = -kam;
t9 = -kap;
t10 = -kdm;
t11 = -kdp;
t12 = -ke;
t13 = -kim;
t14 = -kip;
t15 = -kma;
t16 = -kmi;
t17 = -t2;
t18 = -t3;
t19 = -t4;
t20 = -t5;
t21 = -t6;
t22 = -t7;
RSym = reshape([t8+t12+t20+t22,t5,0.0,kam,0.0,t7,ke,0.0,0.0,0.0,0.0,0.0,kmi,t8+t12+t16,kam,0.0,0.0,0.0,0.0,ke,0.0,0.0,0.0,0.0,0.0,kim,t12+t13+t15,kma,0.0,0.0,0.0,0.0,ke,0.0,0.0,0.0,kim,0.0,t4,t12+t13+t19+t21,t6,0.0,0.0,0.0,0.0,ke,0.0,0.0,0.0,0.0,0.0,t2,t12+t13+t17,kim,0.0,0.0,0.0,0.0,ke,0.0,t3,0.0,0.0,0.0,kam,t8+t12+t18,0.0,0.0,0.0,0.0,0.0,ke,kdm,0.0,0.0,0.0,0.0,0.0,t8+t10+t20+t22,t5,0.0,kam,0.0,t7,0.0,kdp,0.0,0.0,0.0,0.0,kmi,t9+t11+t16,kap,0.0,0.0,0.0,0.0,0.0,kdp,0.0,0.0,0.0,0.0,kip,t11+t14+t15,kma,0.0,0.0,0.0,0.0,0.0,kdm,0.0,0.0,kim,0.0,t4,t10+t13+t19+t21,t6,0.0,0.0,0.0,0.0,0.0,kdp,0.0,0.0,0.0,0.0,t2,t11+t14+t17,kip,0.0,0.0,0.0,0.0,0.0,kdp,t3,0.0,0.0,0.0,kap,t9+t11+t18],[12,12]);
