function RSymFull = RSymFunFull(cr,ki,ka,kp,km,wap,wip,wma,wpa)
%RSYMFUNFULL
%    RSYMFULL = RSYMFUNFULL(CR,KI,KA,KP,KM,WAP,WIP,WMA,WPA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Oct-2021 13:40:02

RSymFull = reshape([-ka-cr.*kp,cr.*kp,0.0,ka,km,-km-ka.*wap,ka.*wap,0.0,0.0,ki.*wip,-ki.*wip-km.*wma,km.*wma,ki,0.0,cr.*kp.*wpa,-ki-cr.*kp.*wpa],[4,4]);
