function RSym = RSymFun(cr,ki,ka,kp,km,wap,wip,wma,wpa)
%RSYMFUN
%    RSYM = RSYMFUN(CR,KI,KA,KP,KM,WAP,WIP,WMA,WPA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Oct-2021 13:40:02

t2 = cr.*kp;
t3 = ka.*wap;
t4 = ki.*wip;
t5 = km.*wma;
t6 = t2.*wpa;
RSym = reshape([-ka-t2,t2,ka,0.0,km,-km-t3,0.0,t3,ki,0.0,-ki-t6,t6,0.0,t4,t5,-t4-t5],[4,4]);
