function out1 = RSymFun(cr,wip,wap,kim,kam,kpi,kmi,kpa,kma)
%RSYMFUN
%    OUT1 = RSYMFUN(CR,WIP,WAP,KIM,KAM,KPI,KMI,KPA,KMA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Aug-2021 11:07:27

t2 = cr.*kpa;
t3 = cr.*kpi;
t4 = kam.*wap;
t5 = kim.*wip;
out1 = reshape([-kam-t3,t3,0.0,kam,kmi,-kmi-t4,t4,0.0,0.0,t5,-kma-t5,kma,kim,0.0,t2,-kim-t2],[4,4]);
