function RSym = RSymFun(cr,ki,ka,kp,km,wap,wip,wma,wpa,wa,wi)
%RSYMFUN
%    RSYM = RSYMFUN(CR,KI,KA,KP,KM,WAP,WIP,WMA,WPA,WA,WI)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Oct-2021 13:40:31

t2 = cr.*kp;
t3 = ki.*wip;
t4 = km.*wma;
t5 = ka.*3.0;
t6 = wa.^2;
t7 = wi.^2;
t8 = wma.^2;
t9 = wma.^3;
t10 = wpa.^2;
t11 = wpa.^3;
t12 = ka.*wa.*2.0;
t14 = ki.*wi.*2.0;
t13 = t5.*wap;
t15 = t2.*wpa;
t16 = ka.*t6;
t17 = t4.*wma;
t18 = t4.*t8;
t19 = t12.*wap;
t20 = t3.*wi.*2.0;
t21 = t2.*t10;
t22 = t2.*t11;
t24 = ki.*t7.*3.0;
t25 = t3.*t7.*3.0;
t23 = t16.*wap;
RSym = reshape([-t2-t5,t2,t5,0.0,0.0,0.0,0.0,0.0,km,-km-ka.*wap.*3.0,0.0,t13,0.0,0.0,0.0,0.0,ki,0.0,-ki-t12-t15,t15,t12,0.0,0.0,0.0,0.0,t3,t4,-t3-t4-ka.*wa.*wap.*2.0,0.0,t19,0.0,0.0,0.0,0.0,t14,0.0,-t14-t16-t21,t21,t16,0.0,0.0,0.0,0.0,t20,t17,-t17-t20-t23,0.0,t23,0.0,0.0,0.0,0.0,t24,0.0,-t22-t24,t22,0.0,0.0,0.0,0.0,0.0,t25,t18,-t18-t25],[8,8]);
