function RSym = RSymFun(cr,cw,a,ki,ka,kp,km,wap,wip,wma,wpa,wmp,wa,wi)
%RSYMFUN
%    RSYM = RSYMFUN(CR,CW,A,KI,KA,KP,KM,WAP,WIP,WMA,WPA,WMP,WA,WI)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    17-Feb-2022 12:26:35

t2 = a.*km;
t3 = cr.*kp;
t4 = cw.*kp;
t5 = ka.*wap;
t6 = ki.*wip;
t7 = km.*wma;
t8 = t2.*wma;
t9 = t3.*wpa;
t10 = t4.*wpa;
t11 = -t5;
t12 = -t6;
RSym = reshape([-ka-t3-t4,t4,t3,ka,0.0,0.0,t2,-t2+t11,0.0,0.0,t5,0.0,km,0.0,-km+t11,0.0,0.0,t5,ki,0.0,0.0,-ki-t9-t10,t10,t9,0.0,t6,0.0,t8,-t8+t12,0.0,0.0,0.0,t6,t7,0.0,-t7+t12],[6,6]);
