function entropyRateSym = entropyRateFunction(c,k12,k14,k21,k23,k32,k34,k41,k43,ss1,ss2,ss3,ss4)
%ENTROPYRATEFUNCTION
%    ENTROPYRATESYM = ENTROPYRATEFUNCTION(C,K12,K14,K21,K23,K32,K34,K41,K43,SS1,SS2,SS3,SS4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    17-Mar-2021 11:31:21

t2 = 1.0./c;
entropyRateSym = k14.*ss4.*log(k14./k41)+k23.*ss3.*log(k23./k32)+k32.*ss2.*log(k32./k23)+k41.*ss1.*log(k41./k14)+k12.*ss2.*log((k12.*t2)./k21)+k43.*ss3.*log((k43.*t2)./k34)+c.*k21.*ss1.*log((c.*k21)./k12)+c.*k34.*ss4.*log((c.*k34)./k43);
