function productionRateSym = productionRateFunction(ss3,ss4)
%PRODUCTIONRATEFUNCTION
%    PRODUCTIONRATESYM = PRODUCTIONRATEFUNCTION(SS3,SS4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    17-Mar-2021 11:30:51

productionRateSym = ss3+ss4;
