function RSym = RSymFun(c,k12,k14,k21,k23,k32,k34,k41,k43)
%RSYMFUN
%    RSYM = RSYMFUN(C,K12,K14,K21,K23,K32,K34,K41,K43)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    17-Mar-2021 11:34:19

t2 = c.*k21;
t3 = c.*k34;
RSym = reshape([-k41-t2,t2,0.0,k41,k12,-k12-k32,k32,0.0,0.0,k23,-k23-k43,k43,k14,0.0,t3,-k14-t3],[4,4]);
