function ETOFFMean = TauONFunction(c,k14,k23,k32,k34,k41,k43,ss1,ss2)
%TAUONFUNCTION
%    ETOFFMEAN = TAUONFUNCTION(C,K14,K23,K32,K34,K41,K43,SS1,SS2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    17-Mar-2021 11:31:20

ETOFFMean = ((k32.*ss2.*(k14+k43+c.*k34))./(k14.*k23+k14.*k43+c.*k23.*k34)+(k41.*ss1.*(k23+k43+c.*k34))./(k14.*k23+k14.*k43+c.*k23.*k34))./(k32.*ss2+k41.*ss1);
